# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c43906dd5afc763a2d5e53bba282a55e81263858a4fc71276b67f57d5131b67a9fc08326b4b00f8f6d27391bafccceda8e9c6b070b10f0e5e9a7ec5e6f470eb

test:
  secret_key_base: 278afc3131d5c635316ef2b6555a0b5b760582d0877eeb74cf59c0f839e14607e3ee38cef1c1e7a996dd4dd1ff91e3793856869e806b3afa148eea110420801e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
